[README] Add instruction for package installation for developers
snap-stanford/relbench pull request #172
Opened 2024-05-27 22:54 UTC by XinweiHe

As titled.

2024-05-28 03:06 UTC, weihua916 commented on README.md
> +pip install pyg-lib -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html
No need.

2024-05-28 05:06 UTC, rusty1s requested changes

2024-05-28 05:06 UTC, rusty1s commented on setup.py
No need to add a `setup.py` - there exists a `pyproject.toml` file already.

2024-05-28 07:28 UTC, XinweiHe commented
Without `setup.py` or `setup.cfg`, `pip install -e .` wouldn't work. Is there a more convenient way to install rel-bench in editable mode

2024-05-28 09:51 UTC, rusty1s commented
It certainly does. What's the error you are seeing?

2024-05-29 22:39 UTC, XinweiHe commented
> I think you may need to upgrade pip to latest version. old version does not work with pyproject.toml

Ah, I see. Let me close this PR then

2024-05-29 22:39 UTC, closed without merging